services:
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      SERVER_PORT: ":8080"

  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8081:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      SERVER_PORT: ":8080"
      DBCONNECTION: "host=postgres port=5432 user=postgres password=postgres dbname=auth_micro_db sslmode=disable"
      DB_DRIVER: "postgres"
      PRIVATE_KEY_PATH: "id_rsa_priv.pem"
    depends_on:
      - postgres

  logger-service:
    build:
      context: ./logger-service
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8082:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      SERVER_PORT: ":8080"
      MONGO_URL: "mongodb://mongo:27017"
      MONGO_USER: "admin"
      MONGO_PASSWORD: "admin"

  mail-service:
    build:
      context: ./mail-service
      dockerfile: ./Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: none
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_FROMNAME: "Max Mustermann"
      MAIL_FROMADDRESS: "max.mustermann@test.com"

  postgres:
    container_name: postgres
    image: 'postgres:16.3-alpine'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USEER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "auth_micro_db"
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data
      - ./dbScripts/authService/public_schema.sql:/docker-entrypoint-initdb.d/public_schema.sql

  mongo:
    image: 'mongo:8.0.0-rc11'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./db-data/mongo/:/data/db

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"

  rabbitmq:
    image: 'rabbitmq:3.13.4-management'
    ports:
      - "5672:5672"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq