services:
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: ./Dockerfile
    restart: always
    ports:
      -
    deploy:
      mode: replicated
      replicas: 1