services:
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      SERVER_PORT: ":8080"

  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8081:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      SERVER_PORT: ":8080"
      DBCONNECTION: "host=postgres port=5432 user=postgres password=postgres dbname=auth_micro_db sslmode=disable"
      DB_DRIVER: "postgres"
      PRIVATE_KEY_PATH: "id_rsa_priv.pem"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: 'postgres:16.3-alpine'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USEER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "auth_micro_db"
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data
      - ./dbScripts/authService/public_schema.sql:/docker-entrypoint-initdb.d/public_schema.sql

  mongo:
    image: 'mongo:8.0.0-rc11'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./db-data/mongo/:/data/db